sudo: required
services:
  - docker

before_install:
  - docker build -t richardkhonan/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true richardkhonan/react-test npm test

after_success:
  - docker build -t richardkhonan/multi-client ./client
  - docker build -t richardkhonan/multi-nginx ./nginx
  - docker build -t richardkhonan/multi-server ./server
  - docker build -t richardkhonan/multi-worker ./worker

  # Log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin

  # Push images to docker hub
  - docker push richardkhonan/multi-client
  - docker push richardkhonan/multi-nginx
  - docker push richardkhonan/multi-server
  - docker push richardkhonan/multi-worker

deploy:
  provider: elasticbeanstalk
  region: ap-southeast-1
  app: multi-container-docker
  env: Multicontainerdocker-env
  bucket_name: elasticbeanstalk-ap-southeast-1-759673436452
  bucket_path: multi-container-docker
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY