sudo: required
services:
  - docker

before_install:
  - docker build -t richardkhonan/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true richardkhonan/react-test npm test

after_success:
  - docker build -t richardkhonan/multi-client ./client
  - docker build -t richardkhonan/multi-nginx ./nginx
  - docker build -t richardkhonan/multi-server ./server
  - docker build -t richardkhonan/multi-worker ./worker

  # Log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin

  # Push images to docker hub
  - docker push richardkhonan/multi-client
  - docker push richardkhonan/multi-nginx
  - docker push richardkhonan/multi-server
  - docker push richardkhonan/multi-worker
